FROM ghcr.io/rocker-org/devcontainer/r-ver:4.5

# Adding R packages for development
RUN install2.r --error roxygen2 tinytest devtools covr rmarkdown knitr

RUN install2.r --error XML igraph servr htmlwidgets

CMD ["bash"]
