FROM ghcr.io/rocker-org/devcontainer/r-ver:4.5

# Architecture-specific variable (built in Docker BuildKit)
ARG TARGETARCH

# Install quarto-cli and the orange-book extension
RUN wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.9.35/quarto-1.9.35-linux-${TARGETARCH}.deb && \
    dpkg -i quarto-1.9.35-linux-${TARGETARCH}.deb && \
    rm quarto-1.9.35-linux-${TARGETARCH}.deb

# System dependencies for R packages
RUN apt-get update && apt-get install -y libuv1t64 && rm -rf /var/lib/apt/lists/*

# Adding R packages for development
RUN install2.r --error roxygen2 tinytest devtools covr rmarkdown knitr

RUN install2.r --error XML igraph servr htmlwidgets

CMD ["bash"]
